### ISSUE TITLE
paper finding

### ISSUE THREAD

**Issue by Nikol-coder** [MKMaS-GUET/KuDA#1]
Hello, I am very interested in your Knowledge-Guided program. Your paper on EMNLP 2024, "Knowledge-Guided Dynamic Modality Attention Fusion Framework for Multimodal Sentiment Analysis. Xinyu Feng, Yuming Lin, Lihua He, You Li, Liang Chang, Ya Zhou "When will it be announced?

**Comment by xyFeng-guet** [comment]
We are delighted that you pay attention to our work. The paper has been published on Arxiv, and the code will be released later. I appreciate your understanding.😄

**Comment by xyFeng-guet** [comment]
Welcome to follow our work; the paper is now available for download at EMNLP2024. The initial version of the code has been updated in the corresponding repository. Thanks.
