### ISSUE TITLE
how can i get pretrained_text.pkl

### ISSUE THREAD

**Issue by FFG0d** [MKMaS-GUET/KuDA#3]
I want to start pre-training myself, but I don’t have the file ./pretrainedModel/pretrained_text.pkl. How can I get it?

**Comment by xyFeng-guet** [comment]
We have now updated the README and placed the download link of pretrained_text.pkl in it. This file is required if you are working with MOSI and MOSEI, but not required for CH-SIMS and CH-SIMSv2. Thanks.
