### ISSUE TITLE
非常好非常棒的工作！！卑微在线求！！！作者大大可以分享这两个缺少的文件嘛？

### ISSUE THREAD

**Issue by jiangshenjie** [MKMaS-GUET/KuDA#4]
├─pretrainedModel
│  ├─BERT
│  └─KnowledgeInjectPretraining
非常好非常棒的工作！！卑微在线求！！！作者大大可以分享pretrainedModel文件夹下这两个缺少的文件嘛？

**Comment by xyFeng-guet** [comment]
非常感谢你的关注（卑微求star🥳）；**BERT**文件夹用于存放huggingface下载的预训练权重，已经在README中放置了链接，或者在终端调用命令同样可以下载；**KnowledgeInjectPretraining**文件夹用于存放第一阶段单模态知识注入的预训练权重，可以自己训练，也可以使用我们之前训练过的（下载链接已放置在README）。由于权重文件大小问题就没有上传至GIthub，敬请谅解！
