### ISSUE TITLE
pretrained_text.pkl

### ISSUE THREAD

**Issue by LeoWade001** [MKMaS-GUET/KuDA#5]
I feel great reading your work. I was very excited when I saw your publication after sending you an email requesting your code. However, I encountered an issue while reproducing your code. During the first step, I ran into a missing pretrained_text.pkl file. I would greatly appreciate it if you could provide this file."

**Comment by xyFeng-guet** [comment]
We are delighted that our work has been helpful in your research. **We have now updated the README and placed the download link of pretrained_text.pkl in it.** This file is required if you are working with MOSI and MOSEI, but not required for CH-SIMS and CH-SIMSv2.
