### ISSUE TITLE
pretrain中seq_lens,fea_dims设置

### ISSUE THREAD

**Issue by Yuan227719** [MKMaS-GUET/KuDA#6]
您好，目前正在复现您的实验结果，pretrain中seq_lens,fea_dims设置为[50, 232, 925]，[768, 177, 25]，当我换成mosei数据集进行预训练时，在训练过程中代码会报错，会出现维度无法对齐情况。具体报错信息为
  File "/home/chrisyuan/model/kuda/models/Encoder_KIAdapter.py", line 202, in forward
    uni_hidden = self.encoder(uni_fea, key_padding_mask)
  File "/home/chrisyuan/miniconda3/envs/KuDA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chrisyuan/model/kuda/models/Encoder_KIAdapter.py", line 113, in forward
    tf_last_hidden_state, tf_hidden_state_list = self.tfencoder(inputs, src_key_padding_mask=key_padding_mask)
  File "/home/chrisyuan/miniconda3/envs/KuDA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chrisyuan/model/kuda/models/Encoder_KIAdapter.py", line 83, in forward
    src = self.pos_encoder(src)
  File "/home/chrisyuan/miniconda3/envs/KuDA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chrisyuan/model/kuda/models/Encoder_KIAdapter.py", line 44, in forward
    embeddings = self.proj(embeddings)
  File "/home/chrisyuan/miniconda3/envs/KuDA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chrisyuan/miniconda3/envs/KuDA/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (14848x35 and 177x128)
由此可见是在进行position_encoding时，线性变换矩阵无法进行相乘导致的报错，但矩阵维度来源于pretrain中seq_lens,fea_dims设置以及模块中的参数默认值，请问seq_lens,fea_dims的值要随着数据集的更换，进而也要发生更改吗？该如何来进行设置来避免出现上述报错？感谢您的开源

**Comment by Yuan227719** [comment]
好像这个代码逻辑是为sim和simv2写的预训练逻辑，换成mosei是不是要改代码逻辑呀

**Comment by xyFeng-guet** [comment]
> 好像这个代码逻辑是为sim和simv2写的预训练逻辑，换成mosei是不是要改代码逻辑呀

是的，目前上传的版本是训练SIMS和SIMSv2的，需要调整一些数据集的参数来适配mosi和mosei，例如序列长度和特征维度，因为数据集间的数据是不一样的

**Comment by Yuan227719** [comment]
> > 好像这个代码逻辑是为sim和simv2写的预训练逻辑，换成mosei是不是要改代码逻辑呀
> 
> 是的，目前上传的版本是训练SIMS和SIMSv2的，需要调整一些数据集的参数来适配mosi和mosei，例如序列长度和特征维度，因为数据集间的数据是不一样的

好的谢谢，请问代码架构会有调整吗？在线等更新哈哈

**Comment by xyFeng-guet** [comment]
> > > 好像这个代码逻辑是为sim和simv2写的预训练逻辑，换成mosei是不是要改代码逻辑呀
> > 
> > 
> > 是的，目前上传的版本是训练SIMS和SIMSv2的，需要调整一些数据集的参数来适配mosi和mosei，例如序列长度和特征维度，因为数据集间的数据是不一样的
> 
> 好的谢谢，请问代码架构会有调整吗？在线等更新哈哈

架构不会有调整的哈，只有参数的改变，还有注意预训练的文本选择问题。

**Comment by Yuan227719** [comment]
还有两个问题想问一下
1，请问mosei和mosi预训练用到的数据集是您提供的那两个text_mosei. pkl和text_ mosi. pkl文件吗？
2，这两个数据集里好像只有文本数据，对于语音和视觉是否是不用进行预训练？



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/11/2024 16:06 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

好像这个代码逻辑是为sim和simv2写的预训练逻辑，换成mosei是不是要改代码逻辑呀

是的，目前上传的版本是训练SIMS和SIMSv2的，需要调整一些数据集的参数来适配mosi和mosei，例如序列长度和特征维度，因为数据集间的数据是不一样的

好的谢谢，请问代码架构会有调整吗？在线等更新哈哈

架构不会有调整的哈，只有参数的改变，还有注意预训练的文本选择问题。

**Comment by xyFeng-guet** [comment]
> 还有两个问题想问一下 1，请问mosei和mosi预训练用到的数据集是您提供的那两个text_mosei. pkl和text_ mosi. pkl文件吗？ 2，这两个数据集里好像只有文本数据，对于语音和视觉是否是不用进行预训练？
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 12/11/2024 16:06 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) | 好像这个代码逻辑是为sim和simv2写的预训练逻辑，换成mosei是不是要改代码逻辑呀 是的，目前上传的版本是训练SIMS和SIMSv2的，需要调整一些数据集的参数来适配mosi和mosei，例如序列长度和特征维度，因为数据集间的数据是不一样的 好的谢谢，请问代码架构会有调整吗？在线等更新哈哈 架构不会有调整的哈，只有参数的改变，还有注意预训练的文本选择问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Q1: 是的，文本是提供的下载链接（经过翻译）
Q2: 语音和视频还是使用SIMS和SIMSv2的数据进行预训练，提供的文本也是SIMS和SIMSv2进行翻译的，而不是mosi和mosei本身的，因为他们没有单模态标签（情感知识）

感谢您的关注！

**Comment by Yuan227719** [comment]
那这样的话，请问在dataset. py当中self. text, self.audio, self. vision是否也要像图示代码一样进行切割？再次感谢



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/11/2024 16:32 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

还有两个问题想问一下 1，请问mosei和mosi预训练用到的数据集是您提供的那两个text_mosei. pkl和text_ mosi. pkl文件吗？ 2，这两个数据集里好像只有文本数据，对于语音和视觉是否是不用进行预训练？
…
---- Replied Message ---- | From | @.> | | Date | 12/11/2024 16:06 | | To | @.> | | Cc | @.>@.> | | Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) | 好像这个代码逻辑是为sim和simv2写的预训练逻辑，换成mosei是不是要改代码逻辑呀 是的，目前上传的版本是训练SIMS和SIMSv2的，需要调整一些数据集的参数来适配mosi和mosei，例如序列长度和特征维度，因为数据集间的数据是不一样的 好的谢谢，请问代码架构会有调整吗？在线等更新哈哈 架构不会有调整的哈，只有参数的改变，还有注意预训练的文本选择问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

Q1: 是的，文本是提供的下载链接（经过翻译）
Q2: 语音和视频还是使用SIMS和SIMSv2的数据进行预训练，提供的文本也是SIMS和SIMSv2进行翻译的，而不是mosi和mosei本身的，因为他们没有单模态标签（情感知识）

感谢您的关注！

**Comment by xyFeng-guet** [comment]
我记得不需要，根据sims和simsv2变就行，因为是同一个数据集

**Comment by Yuan227719** [comment]
好的谢谢感谢开源



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/11/2024 17:48 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

我记得不需要，因为是同一个数据集

**Comment by cloveryz11** [comment]
作者您好
1.请问为什么mosi以及mosei不直接用它自己的pkl的text_bert,audio,vision去预训练不行吗

**Comment by Bernardor006** [comment]
> 好的谢谢感谢开源
> […](#)

请问姐姐 or 哥哥，有调通代码吗，我也是用MOSEI和MOSI去试，但是没调通，如果调通的话，请问具体该修改什么地方呢（小白卑微求解答）

**Comment by Yuan227719** [comment]
我是在我的环境下调通了，不一定你的能调通，你mosei和mosi调不通，可能是其中那个预训练模块用不了，你把他注释掉



---- Replied Message ----
| From | Jinlong ***@***.***> |
| Date | 03/17/2025 19:48 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

好的谢谢感谢开源
…

请问姐姐 or 哥哥，有调通代码吗，我也是用MOSEI和MOSI去试，但是没调通，如果调通的话，请问具体该修改什么地方呢（小白卑微求解答）

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Bernardor006 left a comment (MKMaS-GUET/KuDA#6)

好的谢谢感谢开源
…

请问姐姐 or 哥哥，有调通代码吗，我也是用MOSEI和MOSI去试，但是没调通，如果调通的话，请问具体该修改什么地方呢（小白卑微求解答）

**Comment by Bernardor006** [comment]
> 我是在我的环境下调通了，不一定你的能调通，你mosei和mosi调不通，可能是其中那个预训练模块用不了，你把他注释掉
> […](#)

好嘞，超级谢谢，感谢难以言表！！！！！
那目前就是预训练部分出现问题，现在是能跑通了，但是两阶段法的第一阶段（情感知识注入）就相当于没法用了

**Comment by Yuan227719** [comment]
那模块其实也用处不大吧，我也没看懂预训练作用在哪里



---- Replied Message ----
| From | Jinlong ***@***.***> |
| Date | 03/17/2025 20:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

我是在我的环境下调通了，不一定你的能调通，你mosei和mosi调不通，可能是其中那个预训练模块用不了，你把他注释掉
…

好嘞，超级谢谢，感谢难以言表！！！！！
那目前就是预训练部分出现问题，现在是能跑通了，但是两阶段法的第一阶段（情感知识注入）就相当于没法用了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Bernardor006 left a comment (MKMaS-GUET/KuDA#6)

我是在我的环境下调通了，不一定你的能调通，你mosei和mosi调不通，可能是其中那个预训练模块用不了，你把他注释掉
…

好嘞，超级谢谢，感谢难以言表！！！！！
那目前就是预训练部分出现问题，现在是能跑通了，但是两阶段法的第一阶段（情感知识注入）就相当于没法用了

**Comment by Bernardor006** [comment]
> 那模块其实也用处不大吧，我也没看懂预训练作用在哪里
> […](#)

我也懵懵的，可能还是要再去看下作者的论文
非常感谢你啦，帮我解决一个困扰许久的问题！！！！！

**Comment by Yuan227719** [comment]
之前作者有向我解释过，你去看看关闭的issue



---- Replied Message ----
| From | Jinlong ***@***.***> |
| Date | 03/17/2025 20:44 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

那模块其实也用处不大吧，我也没看懂预训练作用在哪里
…

我也懵懵的，可能还是要再去看下作者的论文
非常感谢你啦，帮我解决一个困扰许久的问题！！！！！

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Bernardor006 left a comment (MKMaS-GUET/KuDA#6)

那模块其实也用处不大吧，我也没看懂预训练作用在哪里
…

我也懵懵的，可能还是要再去看下作者的论文
非常感谢你啦，帮我解决一个困扰许久的问题！！！！！

**Comment by Bernardor006** [comment]
> 之前作者有向我解释过，你去看看关闭的issue
> […](#)

哦哦好的

**Comment by Yuan227719** [comment]
请问你有解决情感注入模块那个问题吗哈哈哈哈



---- Replied Message ----
| From | Jinlong ***@***.***> |
| Date | 03/17/2025 20:48 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

之前作者有向我解释过，你去看看关闭的issue
…

哦哦好的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Bernardor006 left a comment (MKMaS-GUET/KuDA#6)

之前作者有向我解释过，你去看看关闭的issue
…

哦哦好的

**Comment by Bernardor006** [comment]
> 请问你有解决情感注入模块那个问题吗哈哈哈哈
> […](#)

我先看了其他论文，这个还没去细看，过段时间要是有看，不管能不能解决都会再回复。
你可以先看一下最新的几篇论文，MSE-Adapter那篇和DLF那篇也挺好的

**Comment by Yuan227719** [comment]
两篇我都看了是挺好的



---- Replied Message ----
| From | Jinlong ***@***.***> |
| Date | 03/27/2025 20:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

请问你有解决情感注入模块那个问题吗哈哈哈哈
…

我先看了其他论文，这个还没去细看，过段时间要是有看，不管能不能解决都会再回复。
你可以先看一下最新的几篇论文，MSE-Adapter那篇和DLF那篇也挺好的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Bernardor006 left a comment (MKMaS-GUET/KuDA#6)

请问你有解决情感注入模块那个问题吗哈哈哈哈
…

我先看了其他论文，这个还没去细看，过段时间要是有看，不管能不能解决都会再回复。
你可以先看一下最新的几篇论文，MSE-Adapter那篇和DLF那篇也挺好的

**Comment by Yuan227719** [comment]
好的谢谢你



---- Replied Message ----
| From | Jinlong ***@***.***> |
| Date | 03/27/2025 20:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

请问你有解决情感注入模块那个问题吗哈哈哈哈
…

我先看了其他论文，这个还没去细看，过段时间要是有看，不管能不能解决都会再回复。
你可以先看一下最新的几篇论文，MSE-Adapter那篇和DLF那篇也挺好的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Bernardor006 left a comment (MKMaS-GUET/KuDA#6)

请问你有解决情感注入模块那个问题吗哈哈哈哈
…

我先看了其他论文，这个还没去细看，过段时间要是有看，不管能不能解决都会再回复。
你可以先看一下最新的几篇论文，MSE-Adapter那篇和DLF那篇也挺好的

**Comment by Bernardor006** [comment]
> 好的谢谢你
> […](#)

情感注入部分的修改：
1、在6、9层接Adapter：
            for n, adapter in zip([6, 9], self.adapters):  # 【改】
                if n == 6:  # 初始层：合并嵌入层和第3层

2、比例因子k设置为2.0；
3、在TfEncoder中引入归一化：

self.norm = nn.LayerNorm(fea_size)  # 新增输入归一化【改】增加
src = self.norm(src)  # 先归一化【改】增加

4、UnimodalEncoder部分，几个参数需要改！

但在最后面的掩码部分好像还有问题要解决，你可以先按这个改一下！

**Comment by Yuan227719** [comment]
好的谢谢！



---- Replied Message ----
| From | Jinlong ***@***.***> |
| Date | 03/31/2025 12:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MKMaS-GUET/KuDA] pretrain中seq_lens,fea_dims设置 (Issue #6) |

好的谢谢你
…

情感注入部分的修改：
1、在6、9层接Adapter：
for n, adapter in zip([6, 9], self.adapters): # 【改】
if n == 6: # 初始层：合并嵌入层和第3层

2、比例因子k设置为2.0；
3、在TfEncoder中引入归一化：

self.norm = nn.LayerNorm(fea_size) # 新增输入归一化【改】增加
src = self.norm(src) # 先归一化【改】增加

但在最后面的掩码部分好像还有问题要解决，你可以先按这个改一下！

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Bernardor006 left a comment (MKMaS-GUET/KuDA#6)

好的谢谢你
…

情感注入部分的修改：
1、在6、9层接Adapter：
for n, adapter in zip([6, 9], self.adapters): # 【改】
if n == 6: # 初始层：合并嵌入层和第3层

2、比例因子k设置为2.0；
3、在TfEncoder中引入归一化：

self.norm = nn.LayerNorm(fea_size) # 新增输入归一化【改】增加
src = self.norm(src) # 先归一化【改】增加

但在最后面的掩码部分好像还有问题要解决，你可以先按这个改一下！

**Comment by H01H** [comment]
> > 好的谢谢你
> > [...](#)
> 
> 情感注入部分的修改： 1 、在6、9层接Adapter： for n, adapter in zip([6, 9], self.adapters): # 【改】 if n == 6: # 初始层：合并嵌入层和第3层
> 
> 2、比例因子k设置为2.0； 3、在TfEncoder中引入归一化：
> 
> self.norm = nn.LayerNorm(fea_size) # 新增输入归一化【改】增加 src = self.norm(src) # 先归一化【改】增加
> 
> 4、UnimodalEncoder部分，几个参数需要修改！
> 
> 但在最后面的掩码部分希望还有问题要解决，你可以先按这个改一下！

你好  请问mosi和mosei的seq_lens,fea_dims分别是什么？
