### ISSUE TITLE
非常棒的工作，关于训练过程中遇到的一些问题可以讨论一下吗

### ISSUE THREAD

**Issue by serafina-zy** [MKMaS-GUET/KuDA#7]
![image](https://github.com/user-attachments/assets/3a94f945-e71a-43b0-b2f0-37ed6be7dc8c)
如上图，在使用SIMS数据集进行训练时，训练过程中学习率始终为0，我尝试找出问题的原因，但能力有限，自己暂时无法解决

**Comment by xyFeng-guet** [comment]
您好，您可以先通过Debug的方式在模型中逐步寻找问题，仅通过上面的问题我也不太清楚问题出在哪里，可以多运行几个epoch。一般问题是出在数据读取，损失计算等方面

**Comment by serafina-zy** [comment]
好的，我后面发现是pytorch版本的问题，谢谢解答

**Comment by houhhhy** [comment]
> 好的，我后面发现是pytorch版本的问题，谢谢解答

你好，我也出现了这个问题，连结果中 MAE |   Corr |   Acc-7三个值也有问题，可以交流一下解决方法吗
